#!/usr/bin/env python3
import os.path
import tempfile
import subprocess

with tempfile.TemporaryDirectory() as name:
    fname = os.path.join(name, "screenshot.png")
    subprocess.run(
        ["/usr/bin/grim", fname],
        check=True,
        capture_output=True,
        encoding="utf-8",
    )
    subprocess.run(
        ["/usr/bin/gimp", fname],
        check=True,
        capture_output=True,
        encoding="utf-8",
    )
