#!/bin/sh
/bin/echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6
/bin/echo 2 > /proc/sys/net/ipv6/conf/all/accept_ra
/bin/echo 0 > /proc/sys/net/ipv6/conf/br0/disable_ipv6
/bin/echo 2 > /proc/sys/net/ipv6/conf/br0/accept_ra
