#!/bin/bash

export STEAM_RUNTIME="0"
export ROYPUR_STEAM_RUNTIME_PATH="${HOME}/.local/share/Steam/ubuntu12_32"
export ROYPUR_STEAM_BINARY="${ROYPUR_STEAM_RUNTIME_PATH}/steam"
export ROYPUR_CORRECT_PATH=`echo ${LD_LIBRARY_PATH} | grep --ignore-case --fixed-strings --count ${ROYPUR_STEAM_RUNTIME_PATH} | tr --complement --delete 0-9`

if [[ "${ROYPUR_CORRECT_PATH}" == "0" ]]
then
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${ROYPUR_STEAM_RUNTIME_PATH}"
fi

${ROYPUR_STEAM_BINARY}
