#!/bin/bash
XAUTH_FILE_NAME=$(/usr/bin/pgrep --list-full --full "/usr/bin/X" | cut "-d}" -f1 | cut "-d{" -f2)
export XAUTHORITY="/var/run/sddm/{${XAUTH_FILE_NAME}}"
export DISPLAY=:0

/usr/bin/xrandr "--output" "HDMI1" "--set" "Broadcast RGB" "Full"
/usr/bin/xrandr "--output" "HDMI2" "--set" "Broadcast RGB" "Full"
